pipeline:
  name: Dockerfile
  identifier: Dockerfile
  projectIdentifier: CI
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Dockerfile
        identifier: Dockerfile
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.k8s
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: docker:dind
                    shell: Sh
                    command: docker login artifactorycloud.ual.com --username "<+secrets.getValue('account.jfrog-username')>" --password <+secrets.getValue('account.jfrog-passowrd')>
