pipeline:
  name: Dockerfile
  identifier: Dockerfile
  projectIdentifier: CI
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Dockerfile
        identifier: Dockerfile
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.k8s
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              containerSecurityContext:
                privileged: true
                allowPrivilegeEscalation: true
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    connectorRef: account.harnessImage
                    image: docker:dind
                    shell: Sh
                    command: |-
                      touch dockerfile
                      cat > dockerfile <<EOF
                      FROM node:16.20.2
                      RUN apt-get update
                      RUN apt upgrade
                      EOF

                      ls
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harnessImage
                    repo: harness
                    tags:
                      - latest
                    caching: true
              - step:
                  type: Background
                  name: Background_1
                  identifier: Background_1
                  spec:
                    connectorRef: account.harnessImage
                    image: docker:dind
                    shell: Sh
                    privileged: true
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: docker:dind
                    shell: Sh
                    command: |-
                      touch dockerfile
                      cat > dockerfile <<EOF
                      FROM node:16.20.2
                      RUN apt-get update
                      RUN apt upgrade
                      EOF

                      ls


                      docker build dockerfile

                      #docker login artifactorycloud.ual.com --username "<+secrets.getValue('account.jfrog-username')>" --password <+secrets.getValue('account.jfrog-passowrd')>
                    privileged: true
