pipeline:
  name: Docker-Build-Argument
  identifier: DockerBuildArgument
  projectIdentifier: CI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.GitHub
        repoName: gitops2-demo
        build: <+input>
  stages:
    - stage:
        name: Build-Arguments
        identifier: BuildArguments
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.k8s
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushECR
                  name: BuildAndPushECR_1
                  identifier: BuildAndPushECR_1
                  spec:
                    connectorRef: account.awsconnector
                    region: us-east-1
                    account: "123"
                    imageName: kartikeya-test
                    tags:
                      - CI
                    dockerfile: Dockerfile
                    buildArgs:
                      SSH_PRIVATE_KEY: $(cat ~/.ssh/id_rsa)
