pipeline:
  name: Expression-Child
  identifier: ExpressionChild
  projectIdentifier: CI
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: child
        identifier: child
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo <+pipeline.variables.username>
  variables:
    - name: username
      type: String
      description: ""
      required: false
      value: ""
    - name: channel
      type: String
      description: ""
      required: false
      value: <+input>
