pipeline:
  name: Git-Clone
  identifier: GitClone
  projectIdentifier: CI
  orgIdentifier: default
  tags:
    kartikeya: ""
  stages:
    - stage:
        name: Git-Clone
        identifier: GitClone
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: nginx
                    shell: Sh
                    command: echo <+secrets.getValue("account.gauntletuser")>
                    envVariables:
                      IMAGE_TAG: <+stage.variables.VERSION>,latest
                  timeout: 1d 1h
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.k8s
              namespace: kartikeya-new
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        variables:
          - name: VERSION
            type: String
            description: ""
            required: false
            value: <+"0.0.1-"+<+pipeline.sequenceId>>
  variables:
    - name: test1
      type: String
      description: ""
      required: false
      value: test2
  properties:
    ci:
      codebase:
        connectorRef: account.GitHub
        repoName: CI-Usecases
        build: <+input>
        sparseCheckout: []
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
  allowStageExecutions: true
