pipeline:
  name: Git-Clone
  identifier: GitClone
  projectIdentifier: CI
  orgIdentifier: default
  tags:
    kartikeya: ""
  stages:
    - stage:
        name: Git-Clone
        identifier: GitClone
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: |-
                      echo "<+secrets.getValue(<+pipeline.variables.test1>)>"
                      echo "repro done"
                      value="<+secrets.getValue(<+pipeline.variables.test1>)>"
                      echo "repro2"
                      echo <+secrets.getValue("account.textfile")> > /harness/a.txt
                      #echo "textfile"
                    runAsUser: "1000"
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: account.GitHub
                    repoName: gitops-demo
                    depth: 5
                    build:
                      type: commitSha
                      spec:
                        commitSha: cd1a6567f0f469575aed223607cf8014624452e3
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
        variables:
          - name: test2
            type: String
            description: ""
            required: false
            value: "456"
  variables:
    - name: test1
      type: String
      description: ""
      required: false
      value: p_private_key
