pipeline:
  name: Git-Clone
  identifier: GitClone
  projectIdentifier: CI
  orgIdentifier: default
  tags:
    kartikeya: ""
  stages:
    - stage:
        name: Git-Clone
        identifier: GitClone
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: Registry
                    image: ubuntu
                    shell: Sh
                    command: echo $test2
                    outputVariables:
                      - name: test2
                        type: Secret
                        value: <+input>
                  timeout: 1d 1h
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: account.GitHub
                    repoName: gitops-demo
                    depth: 5
                    build:
                      type: commitSha
                      spec:
                        commitSha: cd1a6567f0f469575aed223607cf8014624452e3
                  when:
                    stageStatus: Success
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.k8s
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              containerSecurityContext:
                privileged: false
                allowPrivilegeEscalation: false
              os: Linux
          caching:
            enabled: false
            paths: []
        variables:
          - name: test2
            type: String
            description: ""
            required: false
            value: "456"
    - stage:
        name: test
        identifier: test
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: account.test
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  variables:
                    - name: test
                      type: String
                      default: "false"
                      value: <+input>.allowedValues(true,false,try)
          environment:
            environmentRef: account.testenv
            deployToAll: false
            infrastructureDefinitions: <+input>
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  variables:
    - name: test1
      type: String
      description: ""
      required: false
      value: p_private_key
  properties:
    ci:
      codebase:
        connectorRef: account.GitHub
        repoName: CI-Usecases
        build: <+input>
        sparseCheckout: []
        resources:
          limits:
            cpu: 400m
            memory: 500Mi
  allowStageExecutions: true
