pipeline:
  name: Git-Clone
  identifier: GitClone
  projectIdentifier: CI
  orgIdentifier: default
  tags:
    kartikeya: ""
  stages:
    - stage:
        name: Git-Clone
        identifier: GitClone
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: nginx
                    shell: Sh
                    command: sleep 500
                  timeout: 1d 1h
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harnessImage
                    repo: kartikeya9/ng-labs
                    tags:
                      - "9"
                    caching: false
                    baseImageConnectorRefs:
                      - account.test4
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.k8s
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              containerSecurityContext:
                privileged: false
                allowPrivilegeEscalation: false
              os: Linux
          caching:
            enabled: false
            paths: []
  variables:
    - name: test1
      type: String
      description: ""
      required: false
      value: p_private_key
  properties:
    ci:
      codebase:
        connectorRef: account.GitHub
        repoName: CI-Usecases
        build: <+input>
        sparseCheckout: []
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
  allowStageExecutions: true
