pipeline:
  name: Git-SSH-Connector
  identifier: GitSSHConnector
  projectIdentifier: CI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.GithubSSH
        repoName: gitops2-demo
        build: <+input>
  stages:
    - stage:
        name: git-ssh-windows
        identifier: gitsshwindows
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: echo "hi"
          infrastructure:
            type: VM
            spec:
              type: Pool
              spec:
                poolName: windows-ci-pool
                os: Windows
