pipeline:
  name: Mac
  identifier: Mac
  projectIdentifier: CI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.GitHub
        repoName: CI-Usecases
        build: <+input>
  stages:
    - stage:
        name: Mac
        identifier: Mac
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Cloud
            spec:
              imageSpec:
                imageName: macos_sequoia
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: account.GitHub
                    repoName: CI-Usecases
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      pwd
                      ls
                      echo "before creating directory"
                      mkdir test
                      echo "after creating directory"
                      ls
                      pwd
