pipeline:
  name: Mac
  identifier: Mac
  projectIdentifier: CI
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Mac
        identifier: Mac
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
            paths: []
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Cloud
            spec:
              imageSpec:
                imageName: macos_sequoia
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: account.GitHub
                    repoName: CI-Usecases
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      pwd
                      ls
                      echo "before creating directory"
                      mkdir test
                      echo "after creating directory"
                      ls
                      pwd
          buildIntelligence:
            enabled: false
