pipeline:
  name: Mac
  identifier: Mac
  projectIdentifier: CI
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Mac
        identifier: Mac
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            paths: []
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Cloud
            spec:
              imageSpec:
                imageName: macos_sequoia
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      xcodes installed
                      xcodes select 16.4
                      xcrun simctl list runtimes
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: account.GitHub
                    repoName: CI-Usecases
                    cloneDirectory: /harness/kartik
                    build:
                      type: branch
                      spec:
                        branch: main
          buildIntelligence:
            enabled: false
  properties:
    ci:
      codebase:
        connectorRef: account.GitHub
        repoName: CI-Usecases
        build: <+input>
        sparseCheckout: []
