pipeline:
  name: MySQL-Schema
  identifier: MySQLSchema
  projectIdentifier: CI
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: MySQL
        identifier: MySQL
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: curl -v https://registry1.dso.mil/v2/
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
