pipeline:
  name: Skip
  identifier: Skip
  projectIdentifier: CI
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: skipstep
        identifier: skipstep
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: export skipvar = true
                    outputVariables:
                      - name: skipvar
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: echo hi
                  when:
                    stageStatus: Success
                    condition: <+steps.Run_1.output.script_output> != 'true'
