pipeline:
  name: ssh git clone
  identifier: ssh_git_clone
  projectIdentifier: CI
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ssh git clone
        identifier: ssh_git_clone
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.DockerPassword
                    image: alpine/git
                    shell: Sh
                    command: git clone git@github.com:harness/developer-hub.git
          platform:
            os: Linux
          runtime:
            type: Cloud
            spec: {}
