pipeline:
  name: stepStatus
  identifier: stepStatus
  projectIdentifier: CI
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stepStatus
        identifier: stepStatus
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.k8s
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - stepGroup:
                  name: stepgroup9
                  identifier: stepgroup9
                  steps:
                    - step:
                        type: Run
                        name: Run_1
                        identifier: Run_1
                        spec:
                          connectorRef: account.harnessImage
                          image: nginx
                          shell: Sh
                          command: docker ps -a
                    - step:
                        type: Run
                        name: Run_2
                        identifier: Run_2
                        spec:
                          connectorRef: account.harnessImage
                          image: nginx
                          shell: Sh
                          command: echo <+execution.steps.stepgroup9.steps.Run_1.status>
