pipeline:
  name: stop-background
  identifier: stopbackground
  projectIdentifier: CI
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stop
        identifier: stop
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          execution:
            steps:
              - step:
                  type: Background
                  name: Background_1
                  identifier: Background_1
                  spec:
                    connectorRef: account.DockerPassword
                    image: redis
                    shell: Sh
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      docker stop redis
                      docker rm redis
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
