pipeline:
  name: Windows-Infra-Cloud
  identifier: Windowsinfra
  projectIdentifier: CI
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: WindowsInfra
        identifier: WindowsInfra
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
          platform:
            os: Windows
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: az containerapp revision copy --name scconappcourierdev --resource-group WMS_Development_RG --revision-suffix dev-34 --image wmsconregdev.azurecr.io/courierservice:34
